DROP TABLE IF EXISTS admin_operation_log;
DROP TABLE IF EXISTS announcement;
DROP TABLE IF EXISTS report_evidence;
DROP TABLE IF EXISTS file_record;
DROP TABLE IF EXISTS report;
DROP TABLE IF EXISTS credit_log;
DROP TABLE IF EXISTS review;
DROP TABLE IF EXISTS notification;
DROP TABLE IF EXISTS order_message;
DROP TABLE IF EXISTS order_status_log;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS application;
DROP TABLE IF EXISTS favorite;
DROP TABLE IF EXISTS task_image;
DROP TABLE IF EXISTS task;
DROP TABLE IF EXISTS verification_code;
DROP TABLE IF EXISTS user_profile;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(128) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(16) NOT NULL,
  status VARCHAR(16) NOT NULL,
  verified BOOLEAN NOT NULL DEFAULT FALSE,
  student_no_masked VARCHAR(32),
  login_failures INT NOT NULL DEFAULT 0,
  locked_until TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_profile (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE,
  nickname VARCHAR(30) NOT NULL,
  avatar_url VARCHAR(512),
  gender VARCHAR(8),
  grade VARCHAR(16),
  college VARCHAR(64),
  bio VARCHAR(200),
  campus VARCHAR(32),
  contact VARCHAR(100),
  contact_visible BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE verification_code (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(128) NOT NULL,
  code VARCHAR(6) NOT NULL,
  purpose VARCHAR(20) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  used BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE task (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  publisher_id BIGINT NOT NULL,
  category VARCHAR(32) NOT NULL,
  title VARCHAR(100) NOT NULL,
  description VARCHAR(2000) NOT NULL,
  campus VARCHAR(32) NOT NULL,
  location_detail VARCHAR(128),
  reward_type VARCHAR(16) NOT NULL,
  reward_amount DECIMAL(10,2),
  deadline TIMESTAMP NOT NULL,
  status VARCHAR(20) NOT NULL,
  anonymous BOOLEAN NOT NULL DEFAULT FALSE,
  category_fields CLOB,
  version INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE task_image (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  task_id BIGINT NOT NULL,
  image_url VARCHAR(512) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE favorite (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  task_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE application (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  task_id BIGINT NOT NULL,
  applicant_id BIGINT NOT NULL,
  message VARCHAR(500) NOT NULL,
  status VARCHAR(16) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE orders (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  task_id BIGINT NOT NULL UNIQUE,
  publisher_id BIGINT NOT NULL,
  service_provider_id BIGINT NOT NULL,
  status VARCHAR(24) NOT NULL,
  completion_proof_url VARCHAR(512),
  cancel_reason VARCHAR(500),
  version INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_status_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT NOT NULL,
  from_status VARCHAR(24),
  to_status VARCHAR(24) NOT NULL,
  operator_id BIGINT NOT NULL,
  reason VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_message (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT NOT NULL,
  sender_id BIGINT NOT NULL,
  message_type VARCHAR(8) NOT NULL,
  content VARCHAR(2000),
  image_url VARCHAR(512),
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notification (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  receiver_id BIGINT NOT NULL,
  type VARCHAR(24) NOT NULL,
  title VARCHAR(100) NOT NULL,
  content VARCHAR(500) NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  related_order_id BIGINT,
  related_task_id BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE review (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT NOT NULL,
  reviewer_id BIGINT NOT NULL,
  reviewee_id BIGINT NOT NULL,
  rating TINYINT NOT NULL,
  content VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE credit_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  change_amount INT NOT NULL,
  score_before INT NOT NULL,
  score_after INT NOT NULL,
  reason VARCHAR(100) NOT NULL,
  related_order_id BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
